version: '3.7'

services:
  simple_server:
    build: .
    ports:
      - 80:8080
    tty: true
#    command: tail -f /dev/null
    depends_on:
      - mysql_db
    volumes:
      - ./:/app

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_awesome_db
    volumes:
    - mysql_db_volume:/var/lib/mysql

volumes:
  mysql_db_volume:

# docker-compose up
